// src/utils/logActions.js

const LOG_ACTIONS = {
  // 🔐 인증 관련
  LOGIN: "LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  TOKEN_REFRESH: "TOKEN_REFRESH",
  ACCESS_DENIED: "ACCESS_DENIED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",

  // ✅ TODO 기능
  TODO_CREATE: "TODO_CREATE",
  TODO_UPDATE: "TODO_UPDATE",
  TODO_DELETE: "TODO_DELETE",
  HISTORY_VIEW: "HISTORY_VIEW",

  // 👥 사용자 관리
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  MENU_ACCESS: "MENU_ACCESS",

  // 🛠️ 관리자 설정
  SYSTEM_RESET: "SYSTEM_RESET",
  SYSTEM_BACKUP: "SYSTEM_BACKUP",
  ROLE_UPDATE: "ROLE_UPDATE",
  FORCE_LOGOUT: "FORCE_LOGOUT",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  TAG_UPDATE: "TAG_UPDATE",
  LOG_EXPORT: "LOG_EXPORT",

  // 📊 KPI
  KPI_SUBMIT: "KPI_SUBMIT",
  KPI_UPDATE: "KPI_UPDATE",
  KPI_REVIEW: "KPI_REVIEW",

  // 📬 공지 / 제안
  NOTICE_CREATE: "NOTICE_CREATE",
  NOTICE_UPDATE: "NOTICE_UPDATE",
  NOTICE_DELETE: "NOTICE_DELETE",
  SUGGESTION_SUBMIT: "SUGGESTION_SUBMIT",

  // 📅 캘린더 / 휴가
  SCHEDULE_CREATE: "SCHEDULE_CREATE",
  SCHEDULE_UPDATE: "SCHEDULE_UPDATE",
  SCHEDULE_DELETE: "SCHEDULE_DELETE",
  VACATION_REQUEST: "VACATION_REQUEST",
  VACATION_APPROVE: "VACATION_APPROVE",

  // 📂 게시판
  BOARD_POST_CREATE: "BOARD_POST_CREATE",
  BOARD_POST_EDIT: "BOARD_POST_EDIT",
  BOARD_POST_DELETE: "BOARD_POST_DELETE",

  // 👤 내 정보
  PROFILE_VIEW: "PROFILE_VIEW",
};

const LOG_ACTION_LABELS = {
  // 🔐 인증 관련
  LOGIN: "로그인 성공",
  LOGIN_FAIL: "로그인 실패",
  LOGOUT: "로그아웃",
  TOKEN_REFRESH: "토큰 갱신",
  ACCESS_DENIED: "접근 거부",
  SESSION_EXPIRED: "세션 만료",
  PASSWORD_CHANGE: "비밀번호 변경",

  // ✅ TODO 기능
  TODO_CREATE: "할 일 생성",
  TODO_UPDATE: "할 일 수정",
  TODO_DELETE: "할 일 삭제",
  HISTORY_VIEW: "TODO 히스토리 조회",

  // 👥 사용자 관리
  USER_CREATE: "사용자 등록",
  USER_UPDATE: "사용자 정보 수정",
  USER_DELETE: "사용자 삭제",
  MENU_ACCESS: "메뉴 접근",

  // 🛠️ 관리자 설정
  SYSTEM_RESET: "시스템 초기화",
  SYSTEM_BACKUP: "시스템 백업",
  ROLE_UPDATE: "역할 권한 변경",
  FORCE_LOGOUT: "사용자 강제 로그아웃",
  CATEGORY_UPDATE: "업무/KPI 카테고리 수정",
  TAG_UPDATE: "캘린더 태그 수정",
  LOG_EXPORT: "로그 내보내기",

  // 📊 KPI
  KPI_SUBMIT: "KPI 제출",
  KPI_UPDATE: "KPI 수정",
  KPI_REVIEW: "KPI 검토",

  // 📬 공지 / 제안
  NOTICE_CREATE: "공지사항 작성",
  NOTICE_UPDATE: "공지사항 수정",
  NOTICE_DELETE: "공지사항 삭제",
  SUGGESTION_SUBMIT: "익명 제안 제출",

  // 📅 캘린더 / 휴가
  SCHEDULE_CREATE: "일정 등록",
  SCHEDULE_UPDATE: "일정 수정",
  SCHEDULE_DELETE: "일정 삭제",
  VACATION_REQUEST: "휴가 신청",
  VACATION_APPROVE: "휴가 승인",

  // 📂 게시판
  BOARD_POST_CREATE: "게시글 작성",
  BOARD_POST_EDIT: "게시글 수정",
  BOARD_POST_DELETE: "게시글 삭제",

  // 👤 내 정보
  PROFILE_VIEW: "내 정보 조회",
};

module.exports = { LOG_ACTIONS, LOG_ACTION_LABELS };
